# Generated by Django 4.0.6 on 2022-09-25 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(default=0.0)),
                ('revenue', models.FloatField(default=0.0)),
                ('profit', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyPerformance',
            fields=[
                ('performance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='performance_app.performance')),
                ('date', models.DateField()),
            ],
            bases=('performance_app.performance',),
        ),
        migrations.CreateModel(
            name='HourlyPerformance',
            fields=[
                ('performance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='performance_app.performance')),
                ('datetime', models.DateTimeField()),
            ],
            bases=('performance_app.performance',),
        ),
    ]
